=== SIPp/sipp/sipp.dtd
<!ELEMENT scenario ( CallLengthRepartition | ResponseTimeRepartition | Reference | send | recv | pause | nop | sendCmd | recvCmd | label | timewait)* >
<!ATTLIST scenario name CDATA #IMPLIED >

<!-- BEGIN message commands -->

<!ENTITY % messageCmdCommon '
  start_rtd NMTOKEN #IMPLIED
  rtd NMTOKEN #IMPLIED
  repeat_rtd (true|false) #IMPLIED
  crlf (true|false) #IMPLIED
  next NMTOKEN #IMPLIED
  test NMTOKEN #IMPLIED
  chance NMTOKEN #IMPLIED
  condexec NMTOKEN #IMPLIED
  condexec_inverse NMTOKEN #IMPLIED
  counter NMTOKEN #IMPLIED
  '>

<!ELEMENT send (#PCDATA|action)* >
<!ATTLIST send %messageCmdCommon; >
<!ATTLIST send retrans NMTOKEN #IMPLIED >
<!ATTLIST send lost NMTOKEN #IMPLIED >
<!ATTLIST send start_txn NMTOKEN #IMPLIED >
<!ATTLIST send ack_txn NMTOKEN #IMPLIED >

<!ELEMENT recv ( action? ) >
<!ATTLIST recv %messageCmdCommon; >
<!ATTLIST recv response NMTOKEN #IMPLIED >
<!ATTLIST recv request CDATA #IMPLIED >
<!ATTLIST recv optional (true|false) #IMPLIED >
<!ATTLIST recv ignosesdp (true|false) #IMPLIED >
<!ATTLIST recv rrs (true|false) #IMPLIED >
<!ATTLIST recv auth (true|false) #IMPLIED >
<!ATTLIST recv lost NMTOKEN #IMPLIED >
<!ATTLIST recv timeout NMTOKEN #IMPLIED >
<!ATTLIST recv ontimeout NMTOKEN #IMPLIED >
<!ATTLIST recv regexp_match (true|false) #IMPLIED >
<!ATTLIST recv response_txn NMTOKEN #IMPLIED >

<!ELEMENT pause EMPTY >
<!ATTLIST pause %messageCmdCommon; >
<!ATTLIST pause milliseconds NMTOKEN #IMPLIED >
<!ATTLIST pause variable NMTOKEN #IMPLIED >
<!ATTLIST pause distribution NMTOKEN #IMPLIED >
<!ATTLIST pause sanity_check (true|false) #IMPLIED >

<!ELEMENT nop ( action? ) >
<!ATTLIST nop %messageCmdCommon; >
<!ATTLIST nop display CDATA #IMPLIED >

<!ELEMENT sendCmd ( #PCDATA ) >
<!ATTLIST sendCmd %messageCmdCommon; >
<!ATTLIST sendCmd dest NMTOKEN #IMPLIED >

<!ELEMENT recvCmd ( action? ) >
<!ATTLIST recvCmd %messageCmdCommon; >
<!ATTLIST recvCmd src NMTOKEN #IMPLIED >

<!-- END message commands -->

<!ELEMENT label ( #PCDATA ) >
<!ATTLIST label id NMTOKEN #IMPLIED >

<!ELEMENT ResponseTimeRepartition EMPTY >
<!ATTLIST ResponseTimeRepartition value CDATA #REQUIRED >

<!ELEMENT CallLengthRepartition EMPTY >
<!ATTLIST CallLengthRepartition value CDATA #REQUIRED >

<!ELEMENT action ( add | assign | assignstr | closecon | divide | ereg | error | exec | gettimeofday | index | insert | jump | log | lookup | multiply | pauserestore | replace | rtp_echo | sample | setdest | strcmp | subtract | test | todouble | trim | urldecode | urlencode | verifyauth | warning | closecon )+ >

<!-- BEGIN actions -->

<!ELEMENT ereg EMPTY >
<!ATTLIST ereg assign_to CDATA #REQUIRED >
<!ATTLIST ereg check_it (true|false) "false" >
<!ATTLIST ereg header NMTOKEN #IMPLIED >
<!ATTLIST ereg regexp CDATA #REQUIRED >
<!ATTLIST ereg search_in (msg|hdr|var) "msg" >
<!ATTLIST ereg start_line (true|false) #IMPLIED >
<!ATTLIST ereg variable CDATA #IMPLIED >

<!ELEMENT log EMPTY >
<!ATTLIST log message CDATA #REQUIRED >

<!ELEMENT warning EMPTY >
<!ATTLIST warning message CDATA #REQUIRED >

<!ELEMENT exec EMPTY >
<!-- one of command or int_cmd must be present -->
<!ATTLIST exec command CDATA #IMPLIED >
<!ATTLIST exec int_cmd (stop_now|stop_gracefully|stop_call) "stop_call" >
<!ATTLIST exec play_pcap CDATA #IMPLIED >
<!ATTLIST exec play_pcap_audio CDATA #IMPLIED >
<!ATTLIST exec rtp_stream CDATA #IMPLIED >
<!ATTLIST exec rtp_echo CDATA #IMPLIED >

<!ELEMENT rtp_echo EMPTY >
<!ATTLIST rtp_echo value CDATA #REQUIRED >

<!ELEMENT strcmp EMPTY >
<!ATTLIST strcmp assign_to CDATA #REQUIRED >
<!ATTLIST strcmp value CDATA #REQUIRED >
<!ATTLIST strcmp variable CDATA #REQUIRED >

<!ELEMENT test EMPTY >
<!ATTLIST test assign_to CDATA #REQUIRED >
<!ATTLIST test compare CDATA #REQUIRED >
<!ATTLIST test value CDATA #REQUIRED >
<!ATTLIST test variable CDATA #REQUIRED >

<!ELEMENT assignstr EMPTY >
<!ATTLIST assignstr assign_to CDATA #REQUIRED >
<!ATTLIST assignstr value CDATA #REQUIRED >

<!ELEMENT assign EMPTY >
<!ATTLIST assign assign_to CDATA #REQUIRED >
<!ATTLIST assign value CDATA #IMPLIED >
<!ATTLIST assign variable CDATA #IMPLIED >

<!ELEMENT gettimeofday EMPTY >
<!ATTLIST gettimeofday assign_to CDATA #REQUIRED >

<!ELEMENT insert EMPTY >
<!ATTLIST insert file CDATA #REQUIRED >
<!ATTLIST insert value CDATA #REQUIRED >

<!ELEMENT jump EMPTY>
<!ATTLIST jump value CDATA #IMPLIED>
<!ATTLIST jump variable CDATA #IMPLIED>

<!ELEMENT lookup EMPTY>
<!ATTLIST lookup assign_to CDATA #REQUIRED>
<!ATTLIST lookup file CDATA #REQUIRED>
<!ATTLIST lookup key CDATA #REQUIRED>

<!ELEMENT replace EMPTY>
<!ATTLIST replace value CDATA #REQUIRED>
<!ATTLIST replace file CDATA #REQUIRED>
<!ATTLIST replace line CDATA #REQUIRED>

<!ELEMENT sample EMPTY>
<!ATTLIST sample assign_to CDATA #REQUIRED>
<!ATTLIST sample distribution CDATA #REQUIRED>
<!ATTLIST sample mean CDATA #REQUIRED>
<!ATTLIST sample stdev CDATA #REQUIRED>

<!ELEMENT setdest EMPTY>
<!ATTLIST setdest host CDATA #REQUIRED>
<!ATTLIST setdest port CDATA #REQUIRED>
<!ATTLIST setdest protocol CDATA #REQUIRED>
<!ATTLIST setdest local_port CDATA #IMPLIED>

<!ELEMENT todouble EMPTY>
<!ATTLIST todouble assign_to CDATA #REQUIRED>
<!ATTLIST todouble variable CDATA #IMPLIED>
<!ATTLIST todouble value CDATA #IMPLIED>

<!ELEMENT verifyauth EMPTY>
<!ATTLIST verifyauth assign_to CDATA #REQUIRED>
<!ATTLIST verifyauth username CDATA #REQUIRED>
<!ATTLIST verifyauth password CDATA #REQUIRED>

<!ELEMENT urldecode EMPTY >
<!ATTLIST urldecode variable CDATA #REQUIRED >

<!ELEMENT urlencode EMPTY >
<!ATTLIST urlencode variable CDATA #REQUIRED >

<!ELEMENT closecon EMPTY >

<!-- END actions -->

<!ELEMENT timewait EMPTY >
<!ATTLIST timewait milliseconds CDATA #REQUIRED >

<!ELEMENT Reference EMPTY >
<!ATTLIST Reference variables CDATA #REQUIRED >

<!ELEMENT add EMPTY>
<!ATTLIST add assign_to CDATA #REQUIRED>
<!ATTLIST add value CDATA #IMPLIED>
<!ATTLIST add variable CDATA #IMPLIED>

<!ELEMENT subtract EMPTY>
<!ATTLIST subtract assign_to CDATA #REQUIRED>
<!ATTLIST subtract value CDATA #IMPLIED>
<!ATTLIST subtract variable CDATA #IMPLIED>

<!ELEMENT multiply EMPTY>
<!ATTLIST multiply assign_to CDATA #REQUIRED>
<!ATTLIST multiply value CDATA #IMPLIED>
<!ATTLIST multiply variable CDATA #IMPLIED>

<!ELEMENT divide EMPTY>
<!ATTLIST divide assign_to CDATA #REQUIRED>
<!ATTLIST divide value CDATA #IMPLIED>
<!ATTLIST divide variable CDATA #IMPLIED>

=== SIPp/sipp/regress/github-#0238/uas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario>
  <recv request="INVITE"/>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag00[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: sip:sipp@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <!--

    If you forget start_line="true" here, the headers will be found by value,
    causing '''From: "Tom ...''' to match as the first "To"-header.

  -->
  <recv request="ACK" rrs="true">
    <action>
      <ereg regexp=": *(.*)" search_in="hdr" header="From" start_line="true" assign_to="_,them"/>
      <ereg regexp=": *(.*)" search_in="hdr" header="To" start_line="true" assign_to="_,us"/>
    </action>
  </recv>
  <Reference variables="_"/>

  <send retrans="500">
    <![CDATA[

      BYE [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: [$us]
      To: [$them]
      Call-ID: [call_id]
      CSeq: 2 BYE
      Contact: sip:sipp@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <recv response="200"/>

  <timewait milliseconds="500"/>
</scenario>

=== SIPp/sipp/docs/uas_w_script.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<!-- This program is free software; you can redistribute it and/or      -->
<!-- modify it under the terms of the GNU General Public License as     -->
<!-- published by the Free Software Foundation; either version 2 of the -->
<!-- License, or (at your option) any later version.                    -->
<!--                                                                    -->
<!-- This program is distributed in the hope that it will be useful,    -->
<!-- but WITHOUT ANY WARRANTY; without even the implied warranty of     -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the      -->
<!-- GNU General Public License for more details.                       -->
<!--                                                                    -->
<!-- You should have received a copy of the GNU General Public License  -->
<!-- along with this program; if not, write to the                      -->
<!-- Free Software Foundation, Inc.,                                    -->
<!-- 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA             -->
<!--                                                                    -->
<!--                 Sipp default 'uas' scenario.                       -->
<!--                                                                    -->

<scenario name="Basic UAS responder">
  <!-- By adding rrs="true" (Record Route Sets), the route sets         -->
  <!-- are saved and used for following messages sent. Useful to test   -->
  <!-- against stateful SIP proxies/B2BUAs.                             -->
  <!-- Adding ignoresdp="true" here would ignore the SDP data: that     -->
  <!-- can be useful if you want to reject reINVITEs and keep the       -->
  <!-- media stream flowing.                                            -->
  <recv request="INVITE" crlf="true">
	   <action>
         <ereg regexp="sip:[+1]*(.*?)\@([0123456789.a-zA-Z]*)" search_in="hdr" header="To:" assign_to="1,2,3" />
         <log message="To Match on [$1] - User is [$2] Domain is [$3] "/>
         <ereg regexp="sip:[+1]*([0-9a-zA-Z]*)?\@([0-9.a-zA-Z]*)" search_in="hdr" header="From:" assign_to="4,5,6" />
         <log message="From Match on [$4] - User is [$5] Domain is [$6] "/>
	</action>

  </recv>

  <!-- The '[last_*]' keyword is replaced automatically by the          -->
  <!-- specified header if it was present in the last message received  -->
  <!-- (except if it was a retransmission). If the header was not       -->
  <!-- present or if no message has been received, the '[last_*]'       -->
  <!-- keyword is discarded, and all bytes until the end of the line    -->
  <!-- are also discarded.                                              -->
  <!--                                                                  -->
  <!-- If the specified header was present several times in the         -->
  <!-- message, all occurrences are concatenated (CRLF separated)       -->
  <!-- to be used in place of the '[last_*]' keyword.                   -->

  <send>
    <![CDATA[

      SIP/2.0 180 Ringing
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
      <action>
        <assignstr assign_to="calling" value=""/>
        <assignstr assign_to="called" value=""/>
        <assignstr assign_to="msgDone" value="0"/>
        <assignstr assign_to="counter" value="0"/>
	<log message="executing lua function my_lua_func calling [$5] called [$2]" />
	<exec command="luathread@my_lua_func calling [$5] called [$2] msgDone 0" />
        <log  message="retkey [$retkey] calling = [$calling] called = [$called]"/>
    </action>

  </send>


  <!-- Do a loop looking for the data to be done -->

 <label id="start_of_loop"/>
    <pause milliseconds="100" />
    <!-- retrieve our variables back from our previous read -->
    <nop>
             <action>
                <log message="luaread@[$retkey] 0" />
                <exec command="luaread@[$retkey] 0" />
                <strcmp assign_to="result" variable="msgDone" value="0" />
                <log message="result for msgDone  check = [$msgDone]"/>
                <!-- <log  message="retkey = [$retkey] calling = [$calling] called = [$called]"/> -->
             </action>
   </nop>

  <!-- When we're done processing jump to finished else keep looping -->
  <nop next="finished" test="result"/>

  <!-- Increment the counter and continue looping up to 10 times-->
  <nop>
    <action>
      <add assign_to="counter" value="1"/>
      <test assign_to="flag_limit" variable="counter"
                compare="greater_than_equal" value="100"/>
        <log message="flag_limit=([$flag_limit])" />
    </action>
  </nop>

  <nop next="finished" test="flag_limit" />

  <nop next="start_of_loop"/>

 <label id="finished" />

    <nop>
        <action>
                <!-- Delete the shared memory because we're done -->
                <log message="finished!" />
                <log message="luaread@[$retkey] 1" />
                <exec command="luaread@[$retkey] 1" />
        </action>
  </nop>

  <!-- Send the answer with a translated called number in a custom header -->

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      X-Translated-Called: [$called]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK"
        optional="true"
        rtd="true"
        crlf="true">
  </recv>

  <recv request="BYE">
  </recv>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <!-- Keep the call open for a while in case the 200 is lost to be     -->
  <!-- able to retransmit it if we receive the BYE again.               -->
  <timewait milliseconds="4000"/>


  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== SIPp/sipp/run/scenarios/regIPSEC1.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="registration">

<send retrans="500">
<![CDATA[
REGISTER sip:ims.mnc001.mcc001.3gppnetwork.org SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:3062;branch=[branch]
Max-Forwards: 20
From: "alice" <sip:001019901003516@ims.mnc001.mcc001.3gppnetwork.org>;tag=[call_number]
To: "alice" <sip:001019901003516@ims.mnc001.mcc001.3gppnetwork.org>
P-Access-Network-Info: 3GPP-UTRAN-TDD;utran-cell-id-3gpp=C359A3913B20E
Call-ID: reg///[call_id]
CSeq: 1 REGISTER
Contact: <sip:alice@[local_ip]:3062>
Expires: 300
Content-Length: 0
Security-Client: ipsec-3gpp; alg=hmac-md5-96; ealg=des-ede3-cbc; spi-c=2721834714; spi-s=1075014941; port-c=12345; port-s=3062,ipsec-3gpp; alg=hmac-md5-96; ealg=aes-cbc; spi-c=2721834714; spi-s=1075014941; port-c=12345; port-s=3062,ipsec-3gpp; alg=hmac-md5-96; ealg=null; spi-c=2721834714; spi-s=1075014941; port-c=12345; port-s=3062,ipsec-3gpp; alg=hmac-sha-1-96; ealg=des-ede3-cbc; spi-c=2721834714; spi-s=1075014941; port-c=12345; port-s=3062,ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; spi-c=2721834714; spi-s=1075014941; port-c=12345; port-s=3062,ipsec-3gpp; alg=hmac-sha-1-96; ealg=null; spi-c=2721834714; spi-s=1075014941; port-c=12345; port-s=3062
User-Agent: Sipp v1.1-TLS, version 20061124
Authorization: Digest username="001019901003516@ims.mnc001.mcc001.3gppnetwork.org", realm="ims.mnc001.mcc001.3gppnetwork.org"
Supported: path
]]>
</send>

<recv response="100" optional="true"/>

<recv response="401" auth="true" rtd="true">
<action>
	<ereg regexp=".*" search_in="hdr" header="Security-Server:" assign_to="1" />

	<ereg regexp="ealg=([[:alnum:]-]*)" search_in="[$1]" assign_to="2,8" />
	<ereg regexp="[^e]alg=([[:alnum:]-]*)" search_in="[$1]" assign_to="3,9" />
	<ereg regexp="spi-c=([^;]*)" search_in="[$1]" assign_to="4,10" />
	<ereg regexp="spi-s=([^;]*)" search_in="[$1]" assign_to="5,11" />
	<ereg regexp="port-c=([0-9]*)" search_in="[$1]" assign_to="6,12" />
	<ereg regexp="port-s=([0-9]*)" search_in="[$1]" assign_to="7,13" />

  <exec command="echo DEBUG [local_ip]->[remote_ip] spi-c=[$10]; spi-s=[$11]; port-c=[$12]; port-s=[$13]; ealg=[$8]; alg=[$9]; ck=[ck_key]; ik=[ik_key] " />
	
	<exec command="scripts/ipsec_E_Out_Req.sh [local_ip] 12345 [remote_ip] [$13] [$11] [$8] 0x[ck_key] [$9] 0x[ik_key] " />
	<exec command="scripts/ipsec_E_Out_Rpl.sh [local_ip] 3062 [remote_ip] [$12] [$10] [$8] 0x[ck_key] [$9] 0x[ik_key] " />
	<exec command="scripts/ipsec_E_Inc_Req.sh [local_ip] 3062 [remote_ip] [$12] 2028  [$8] 0x[ck_key] [$9] 0x[ik_key] " />
	<exec command="scripts/ipsec_E_Inc_Rpl.sh [local_ip] 12345 [remote_ip] [$13] 1024  [$8] 0x[ck_key] [$9] 0x[ik_key] " />
	
	<exec command="echo SEQUENTIAL > spis.csv" />
	<exec command="echo '[$10];[$11];[$12];[$13]' >> spis.csv" />
  </action>
</recv>


<ResponseTimeRepartition value="10, 20"/>
<CallLengthRepartition value="10"/>
	
</scenario>

=== SIPp/sipp/regress/github-#0862/uas.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario name="uas-rtp-after-multipart-invite">

  <recv request="INVITE" rrs="true"/>

  <send>
    <![CDATA[

      SIP/2.0 180 Ringing
      [last_Via:]
      [last_Record-Route:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_Record-Route:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 8 0
      a=rtpmap:8 PCMA/8000
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK" rrs="true"/>

  <nop>
    <action>
      <exec rtp_stream="beep_1sec_50x160b.alaw,-1,8,PCMA/8000"/>
    </action>
  </nop>

  <pause milliseconds="800"/>

  <send start_txn="bye" retrans="500">
    <![CDATA[

      BYE [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      [routes]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      CSeq: [cseq] BYE
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <recv response="200" response_txn="bye"/>

</scenario>

=== SIPp/sipp/regress/github-header-values/uas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario>
  <recv request="INVITE"/>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      Via: [last_Via!]
      From: [last_From!]
      To: [last_To!];tag=[pid]SIPpTag00[call_number]
      Call-ID: [last_Call-ID!]
      CSeq: [last_CSeq!]
      Contact: sip:sipp@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <!--

    If you forget start_line="true" here, the headers will be found by value,
    causing '''From: "Tom ...''' to match as the first "To"-header.

  -->
  <recv request="ACK" rrs="true">
    <action>
      <ereg regexp=": *(.*)" search_in="hdr" header="From" start_line="true" assign_to="_,them"/>
      <ereg regexp=": *(.*)" search_in="hdr" header="To" start_line="true" assign_to="_,us"/>
      <log message="LAST Via: [last_Via!]"/>
      <log message="LAST From: [last_From!]"/>
      <log message="LAST To: [last_To!]"/>
    </action>
  </recv>
  <Reference variables="_"/>

  <send retrans="500">
    <![CDATA[

      BYE [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: [$us]
      To: [$them]
      Call-ID: [call_id]
      CSeq: 2 BYE
      Contact: sip:sipp@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <recv response="200"/>

  <timewait milliseconds="500"/>  
</scenario>

=== SIPp/sipp/regress/github-#0801/uas_timeout_test.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="UAS timeout test - intentionally slow">
  <recv request="INVITE" crlf="true">
  </recv>

  <send>
    <![CDATA[
      SIP/2.0 100 Trying
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0
    ]]>
  </send>

  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[local_ip_type] [local_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 0
      a=rtpmap:0 PCMU/8000
    ]]>
  </send>

  <recv request="ACK">
  </recv>

  <!-- Intentionally delay before sending BYE - sleep for 2 seconds -->
  <pause milliseconds="2000"/>

  <send>
    <![CDATA[
      BYE sip:[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      [last_From:];tag=[pid]SIPpTag01[call_number]
      [last_To:]
      [last_Call-ID:]
      CSeq: [cseq] BYE
      Content-Length: 0
    ]]>
  </send>

  <recv response="200">
  </recv>

</scenario>
