=== SIPp/sipp/sipp.dtd
<!ELEMENT scenario ( CallLengthRepartition | ResponseTimeRepartition | Reference | send | recv | pause | nop | sendCmd | recvCmd | label | timewait)* >
<!ATTLIST scenario name CDATA #IMPLIED >

<!-- BEGIN message commands -->

<!ENTITY % messageCmdCommon '
  start_rtd NMTOKEN #IMPLIED
  rtd NMTOKEN #IMPLIED
  repeat_rtd (true|false) #IMPLIED
  crlf (true|false) #IMPLIED
  next NMTOKEN #IMPLIED
  test NMTOKEN #IMPLIED
  chance NMTOKEN #IMPLIED
  condexec NMTOKEN #IMPLIED
  condexec_inverse NMTOKEN #IMPLIED
  counter NMTOKEN #IMPLIED
  '>

<!ELEMENT send (#PCDATA|action)* >
<!ATTLIST send %messageCmdCommon; >
<!ATTLIST send retrans NMTOKEN #IMPLIED >
<!ATTLIST send lost NMTOKEN #IMPLIED >
<!ATTLIST send start_txn NMTOKEN #IMPLIED >
<!ATTLIST send ack_txn NMTOKEN #IMPLIED >

<!ELEMENT recv ( action? ) >
<!ATTLIST recv %messageCmdCommon; >
<!ATTLIST recv response NMTOKEN #IMPLIED >
<!ATTLIST recv request CDATA #IMPLIED >
<!ATTLIST recv optional (true|false) #IMPLIED >
<!ATTLIST recv ignosesdp (true|false) #IMPLIED >
<!ATTLIST recv rrs (true|false) #IMPLIED >
<!ATTLIST recv auth (true|false) #IMPLIED >
<!ATTLIST recv lost NMTOKEN #IMPLIED >
<!ATTLIST recv timeout NMTOKEN #IMPLIED >
<!ATTLIST recv ontimeout NMTOKEN #IMPLIED >
<!ATTLIST recv regexp_match (true|false) #IMPLIED >
<!ATTLIST recv response_txn NMTOKEN #IMPLIED >

<!ELEMENT pause EMPTY >
<!ATTLIST pause %messageCmdCommon; >
<!ATTLIST pause milliseconds NMTOKEN #IMPLIED >
<!ATTLIST pause variable NMTOKEN #IMPLIED >
<!ATTLIST pause distribution NMTOKEN #IMPLIED >
<!ATTLIST pause sanity_check (true|false) #IMPLIED >

<!ELEMENT nop ( action? ) >
<!ATTLIST nop %messageCmdCommon; >
<!ATTLIST nop display CDATA #IMPLIED >

<!ELEMENT sendCmd ( #PCDATA ) >
<!ATTLIST sendCmd %messageCmdCommon; >
<!ATTLIST sendCmd dest NMTOKEN #IMPLIED >

<!ELEMENT recvCmd ( action? ) >
<!ATTLIST recvCmd %messageCmdCommon; >
<!ATTLIST recvCmd src NMTOKEN #IMPLIED >

<!-- END message commands -->

<!ELEMENT label ( #PCDATA ) >
<!ATTLIST label id NMTOKEN #IMPLIED >

<!ELEMENT ResponseTimeRepartition EMPTY >
<!ATTLIST ResponseTimeRepartition value CDATA #REQUIRED >

<!ELEMENT CallLengthRepartition EMPTY >
<!ATTLIST CallLengthRepartition value CDATA #REQUIRED >

<!ELEMENT action ( add | assign | assignstr | closecon | divide | ereg | error | exec | gettimeofday | index | insert | jump | log | lookup | multiply | pauserestore | replace | rtp_echo | sample | setdest | strcmp | subtract | test | todouble | trim | urldecode | urlencode | verifyauth | warning | closecon )+ >

<!-- BEGIN actions -->

<!ELEMENT ereg EMPTY >
<!ATTLIST ereg assign_to CDATA #REQUIRED >
<!ATTLIST ereg check_it (true|false) "false" >
<!ATTLIST ereg header NMTOKEN #IMPLIED >
<!ATTLIST ereg regexp CDATA #REQUIRED >
<!ATTLIST ereg search_in (msg|hdr|var) "msg" >
<!ATTLIST ereg start_line (true|false) #IMPLIED >
<!ATTLIST ereg variable CDATA #IMPLIED >

<!ELEMENT log EMPTY >
<!ATTLIST log message CDATA #REQUIRED >

<!ELEMENT warning EMPTY >
<!ATTLIST warning message CDATA #REQUIRED >

<!ELEMENT exec EMPTY >
<!-- one of command or int_cmd must be present -->
<!ATTLIST exec command CDATA #IMPLIED >
<!ATTLIST exec int_cmd (stop_now|stop_gracefully|stop_call) "stop_call" >
<!ATTLIST exec play_pcap CDATA #IMPLIED >
<!ATTLIST exec play_pcap_audio CDATA #IMPLIED >
<!ATTLIST exec rtp_stream CDATA #IMPLIED >
<!ATTLIST exec rtp_echo CDATA #IMPLIED >

<!ELEMENT rtp_echo EMPTY >
<!ATTLIST rtp_echo value CDATA #REQUIRED >

<!ELEMENT strcmp EMPTY >
<!ATTLIST strcmp assign_to CDATA #REQUIRED >
<!ATTLIST strcmp value CDATA #REQUIRED >
<!ATTLIST strcmp variable CDATA #REQUIRED >

<!ELEMENT test EMPTY >
<!ATTLIST test assign_to CDATA #REQUIRED >
<!ATTLIST test compare CDATA #REQUIRED >
<!ATTLIST test value CDATA #REQUIRED >
<!ATTLIST test variable CDATA #REQUIRED >

<!ELEMENT assignstr EMPTY >
<!ATTLIST assignstr assign_to CDATA #REQUIRED >
<!ATTLIST assignstr value CDATA #REQUIRED >

<!ELEMENT assign EMPTY >
<!ATTLIST assign assign_to CDATA #REQUIRED >
<!ATTLIST assign value CDATA #IMPLIED >
<!ATTLIST assign variable CDATA #IMPLIED >

<!ELEMENT gettimeofday EMPTY >
<!ATTLIST gettimeofday assign_to CDATA #REQUIRED >

<!ELEMENT insert EMPTY >
<!ATTLIST insert file CDATA #REQUIRED >
<!ATTLIST insert value CDATA #REQUIRED >

<!ELEMENT jump EMPTY>
<!ATTLIST jump value CDATA #IMPLIED>
<!ATTLIST jump variable CDATA #IMPLIED>

<!ELEMENT lookup EMPTY>
<!ATTLIST lookup assign_to CDATA #REQUIRED>
<!ATTLIST lookup file CDATA #REQUIRED>
<!ATTLIST lookup key CDATA #REQUIRED>

<!ELEMENT replace EMPTY>
<!ATTLIST replace value CDATA #REQUIRED>
<!ATTLIST replace file CDATA #REQUIRED>
<!ATTLIST replace line CDATA #REQUIRED>

<!ELEMENT sample EMPTY>
<!ATTLIST sample assign_to CDATA #REQUIRED>
<!ATTLIST sample distribution CDATA #REQUIRED>
<!ATTLIST sample mean CDATA #REQUIRED>
<!ATTLIST sample stdev CDATA #REQUIRED>

<!ELEMENT setdest EMPTY>
<!ATTLIST setdest host CDATA #REQUIRED>
<!ATTLIST setdest port CDATA #REQUIRED>
<!ATTLIST setdest protocol CDATA #REQUIRED>
<!ATTLIST setdest local_port CDATA #IMPLIED>

<!ELEMENT todouble EMPTY>
<!ATTLIST todouble assign_to CDATA #REQUIRED>
<!ATTLIST todouble variable CDATA #IMPLIED>
<!ATTLIST todouble value CDATA #IMPLIED>

<!ELEMENT verifyauth EMPTY>
<!ATTLIST verifyauth assign_to CDATA #REQUIRED>
<!ATTLIST verifyauth username CDATA #REQUIRED>
<!ATTLIST verifyauth password CDATA #REQUIRED>

<!ELEMENT urldecode EMPTY >
<!ATTLIST urldecode variable CDATA #REQUIRED >

<!ELEMENT urlencode EMPTY >
<!ATTLIST urlencode variable CDATA #REQUIRED >

<!ELEMENT closecon EMPTY >

<!-- END actions -->

<!ELEMENT timewait EMPTY >
<!ATTLIST timewait milliseconds CDATA #REQUIRED >

<!ELEMENT Reference EMPTY >
<!ATTLIST Reference variables CDATA #REQUIRED >

<!ELEMENT add EMPTY>
<!ATTLIST add assign_to CDATA #REQUIRED>
<!ATTLIST add value CDATA #IMPLIED>
<!ATTLIST add variable CDATA #IMPLIED>

<!ELEMENT subtract EMPTY>
<!ATTLIST subtract assign_to CDATA #REQUIRED>
<!ATTLIST subtract value CDATA #IMPLIED>
<!ATTLIST subtract variable CDATA #IMPLIED>

<!ELEMENT multiply EMPTY>
<!ATTLIST multiply assign_to CDATA #REQUIRED>
<!ATTLIST multiply value CDATA #IMPLIED>
<!ATTLIST multiply variable CDATA #IMPLIED>

<!ELEMENT divide EMPTY>
<!ATTLIST divide assign_to CDATA #REQUIRED>
<!ATTLIST divide value CDATA #IMPLIED>
<!ATTLIST divide variable CDATA #IMPLIED>

=== SIPp/sipp/regress/github-#0196/uas.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario name="iinv-o200-obye.xml -- wjd 2014">

  <recv request="INVITE" rrs="true"/>

  <send>
    <![CDATA[

      SIP/2.0 180 Ringing
      [last_Via:]
      [last_Record-Route:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_Record-Route:]
      [last_From:]
      [last_To:];tag=[pid]SIPpTag01[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [custom_media_port] RTP/AVP 8 0
      a=rtpmap:8 PCMA/8000
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv request="ACK" rrs="true">
    <action>
      <ereg regexp=": *(.*)" search_in="hdr" header="To" assign_to="_,us"/><!-- with tag -->
      <ereg regexp=": *(.*)" search_in="hdr" header="From" assign_to="_,them"/>
    </action>
  </recv>
  <Reference variables="_"/>

  <!-- Wait for the other side to send some RTP -->
  <pause milliseconds="1000"/>

  <send start_txn="bye" retrans="500">
    <![CDATA[

      BYE [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      [routes]
      From: [$us]
      To: [$them]
      [last_Call-ID:]
      CSeq: [cseq] BYE
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <recv response="200" response_txn="bye"/>

</scenario><!-- vim: set ts=8 sw=2 sts=2 et ai: -->

=== SIPp/sipp/sipp_scenarios/pfca_uas_both_crypto_simple_nullsha180.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Basic MCD UAS">
  <recv request="INVITE" crlf="true">
    <action>
      <!-- Save the INVITE's CSeq header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="CSeq:" check_it="true" assign_to="1" />
      <!-- Save the INVITE's Via header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="Via:" check_it="true" assign_to="2" />
    </action>
  </recv>

  <!-- NOTE:  The INVITE's Via/CSeq headers are used explicitly here -->
  <send>
    <![CDATA[

      SIP/2.0 180 Ringing
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Require: 100rel
      RSeq: 1
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <recv request="PRACK">
  </recv>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Server: VIRTUAL Mitel-3300-ICP-12.0.1.99
      Content-Length: 0

    ]]>
  </send>

  <!-- NOTE:  The INVITE's Via/CSeq headers are used explicitly here -->
  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      Via: [$2]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      CSeq: [$1]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=16002 0 0 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [rtpstream_audio_port] RTP/AVP 0 18 9 103 8 101
      a=crypto:[cryptotag1audio] [cryptosuitenullsha1801audio] inline:[cryptokeyparams1audio]
      a=rtcp:[rtpstream_audio_port+1]
      a=sendrecv
      a=rtpmap:0 PCMU/8000
      a=rtpmap:18 G729/8000
      a=rtpmap:9 G722/16000
      a=fmtp:9 bitrate=64000
      a=rtpmap:103 G7221/16000
      a=fmtp:103 bitrate=32000
      a=rtpmap:8 PCMA/8000
      a=rtpmap:101 telephone-event/8000
      a=fmtp:101 0-11,16
      m=video [rtpstream_video_port] RTP/AVP 99 98 96 97
      a=crypto:[cryptotag1video] [cryptosuitenullsha1801video] inline:[cryptokeyparams1video]
      b=TIAS:1536000
      b=AS:1597
      a=maxprate:192.0
      a=rtcp:[rtpstream_video_port+1]
      a=rtpmap:99 H264/90000
      a=fmtp:99 profile-level-id=64000d; max-mbps=108000; max-fs=3600; max-br=1280; packetization-mode=1
      a=rtpmap:98 H264/90000
      a=fmtp:98 profile-level-id=64000d; max-mbps=108000; max-fs=3600; max-br=1280; packetization-mode=0
      a=rtpmap:96 H264/90000
      a=fmtp:96 profile-level-id=42800d; max-mbps=108000; max-fs=3600; max-br=1280; packetization-mode=0
      a=rtpmap:97 H264/90000
      a=fmtp:97 profile-level-id=42800d; max-mbps=108000; max-fs=3600; max-br=1280; packetization-mode=1

    ]]>
  </send>

  <nop>
    <action>
        <exec rtp_echo="startaudio,0,PCMU/8000" />
        <exec rtp_echo="startvideo,99,H264/90000" />
    </action>
  </nop>

  <recv request="ACK">
  </recv>

  <recv request="BYE">
  </recv>

  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Length: 0
    ]]>
  </send>

  <nop>
    <action>
        <exec rtp_echo="stopaudio,0,PCMU/8000" />
        <exec rtp_echo="stopvideo,99,H264/90000" />
    </action>
  </nop>



  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== SIPp/sipp/regress/github-#0196/uac.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario name="oinv-i200-ibye.xml -- wjd 2014">

  <send retrans="500" start_txn="invite">
    <![CDATA[

      INVITE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: sip:[service]@[local_ip]:[local_port];tag=[pid]SIPpTag00[call_number]
      To: sip:[service]@[remote_ip]:[remote_port]
      Call-ID: [call_id]
      CSeq: [cseq] INVITE
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=user1 53655765 2353687637 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 8 0
      a=rtpmap:8 PCMA/8000
      a=rtpmap:0 PCMU/8000

    ]]>
  </send>

  <recv response="100" optional="true" response_txn="invite"/>

  <recv response="180" optional="true" response_txn="invite"/>

  <recv response="183" optional="true" response_txn="invite"/>

  <recv response="200" rrs="true" response_txn="invite"/>

  <send ack_txn="invite">
    <![CDATA[

      ACK [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      [routes]
      From: sip:[service]@[local_ip]:[local_port];tag=[pid]SIPpTag00[call_number]
      To: sip:[service]@[remote_ip]:[remote_port][peer_tag_param]
      Call-ID: [call_id]
      CSeq: [cseq] ACK
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <!-- Send some audio to avoid rtptimeout timers kicking in. -->
  <nop>
    <action>
      <exec rtp_stream="beep_1sec_50x160b.alaw,-1,8"/>
    </action>
  </nop>

  <recv request="BYE"/>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_Record-Route:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Content-Length: 0

    ]]>
  </send>

  <timewait milliseconds="1000"/><!-- retransmit 200's for a while -->

</scenario>

=== SIPp/sipp/regress/github-#0260/uas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario>
  <recv request="INVITE"/>

  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      [last_Contact]
      [last_via]
      From: [last_From:value]
      To: [last_To:value];tag=[pid]SIPpTag00[call_number]
      Call-ID: [last_Call-ID:value]
      CSeq: [last_CSeq:value]
      Contact: sip:sipp@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <recv request="ACK" rrs="true">
    <action>
      <log message="LAST Contact|[last_Contact]" />
      <log message="LAST Contact:|[last_Contact:]" />
      <log message="LAST Contact:uri|[last_Contact:uri]"/>
      <log message="LAST Via:value[last_Via:value]"/>
      <log message="LAST From:value|[last_From:value]"/>
      <log message="LAST To:value|[last_To:value]"/>
      <log message="LAST To:uri|[last_To:uri]"/>
      <log message="LAST From:param.tag|[last_From:param.tag]"/>
    </action>
  </recv>

  <send retrans="500">
    <![CDATA[

      BYE [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: [last_To:value]
      To: [last_From:value]
      Call-ID: [call_id]
      CSeq: 2 BYE
      Contact: sip:sipp@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <recv response="200"/>

  <timewait milliseconds="500"/>  
</scenario>

=== SIPp/sipp/sipp_scenarios/mcd_register.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Basic MCD UAS">
  <recv request="REGISTER" crlf="true">
    <action>
      <!-- 
       NOTES:  
       1- Variable $1 contains the whole "<...>" expression
       2- Variable $2 contains the substring "..." (enclosed in-between the angle-brackets)
       
       RESTRICTION:
       ALL variables MUST be used - in this case $1 is assigned the contents of $2 so SIPP is happy
       -->
      <ereg regexp="<(.*)>" search_in="hdr" header="Contact:" check_it="true" assign_to="1,2" />
      <assign assign_to="1" variable="2"/>
    </action>
  </recv>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Allow: INVITE,BYE,CANCEL,ACK,INFO,PRACK,OPTIONS,SUBSCRIBE,NOTIFY,REFER,REGISTER,UPDATE
      [last_Contact:]
      Expires: 86400
      P-Login: mihotdesk
      Date: Wed, 14 May 2014 20:26:35 GMT
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Length: 0 

    ]]>
  </send>

  <!--
  <send retrans="500">
    <![CDATA[

      NOTIFY [$2] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch-2]
      Max-Forwards: 70 
      Allow: INVITE,BYE,CANCEL,ACK,INFO,PRACK,OPTIONS,SUBSCRIBE,NOTIFY,REFER,REGISTER,UPDATE
      From: "mwiapp" <sip:mwiapp@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[local_ip]:[local_port]>
      Call-ID: [call_id]
      CSeq: 1 NOTIFY
      Contact: "mwiapp" <sip:mwiapp@[local_ip]:[local_port]>
      Event: message-summary
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Type: application/simple-message-summary
      Content-Length: [len]

      Messages-Waiting: no

    ]]>
  </send>

  <recv response="489"
        optional="true">
  </recv>
  -->

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== SIPp/sipp/sipp_scenarios/pfca_uas_audio_crypto_simple_g711a.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="Basic MCD UAS">
  <recv request="INVITE" crlf="true">
    <action>
      <!-- Save the INVITE's CSeq header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="CSeq:" check_it="true" assign_to="1" />
      <!-- Save the INVITE's Via header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="Via:" check_it="true" assign_to="2" />
    </action>
  </recv>

  <!-- NOTE:  The INVITE's Via/CSeq headers are used explicitly here -->
  <send>
    <![CDATA[

      SIP/2.0 180 Ringing
      [last_Via:]
      [last_From:]
      [last_To:];tag=[call_number]
      [last_Call-ID:]
      [last_CSeq:]
      Require: 100rel
      RSeq: 1
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Content-Length: 0

    ]]>
  </send>

  <recv request="PRACK">
  </recv>

  <send>
    <![CDATA[

      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Server: VIRTUAL Mitel-3300-ICP-12.0.1.99
      Content-Length: 0

    ]]>
  </send>

  <!-- NOTE:  The INVITE's Via/CSeq headers are used explicitly here -->
  <send retrans="500">
    <![CDATA[

      SIP/2.0 200 OK
      Via: [$2]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      CSeq: [$1]
      Contact: <sip:[local_ip]:[local_port];transport=[transport]>
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Type: application/sdp
      Content-Length: [len]

      v=0
      o=16002 0 0 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [rtpstream_audio_port] RTP/AVP 8 0 18 9 103 101
      a=crypto:[cryptotag1audio] [cryptosuiteaescm128sha1801audio] inline:[cryptokeyparams1audio]
      a=rtcp:[rtpstream_audio_port+1]
      a=sendrecv
      a=rtpmap:8 PCMA/8000
      a=rtpmap:0 PCMU/8000
      a=rtpmap:18 G729/8000
      a=rtpmap:9 G722/16000
      a=fmtp:9 bitrate=64000
      a=rtpmap:103 G7221/16000
      a=fmtp:103 bitrate=32000
      a=rtpmap:101 telephone-event/8000
      a=fmtp:101 0-11,16

    ]]>
  </send>

  <nop>
    <action>
      <exec rtp_echo="startaudio,8,PCMA/8000" />
    </action>
  </nop>

  <recv request="ACK">
  </recv>

  <recv request="BYE">
  </recv>
  
  <send>
    <![CDATA[
      SIP/2.0 200 OK
      [last_Via:]
      [last_From:]
      [last_To:]
      [last_Call-ID:]
      [last_CSeq:]
      Server: VIRTUAL Mitel-3300-ICP 12.0.1.99
      Content-Length: 0
    ]]>
  </send>

  <nop>
    <action>
      <exec rtp_echo="stopaudio,8,PCMA/8000" />
    </action>
  </nop>



  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>

=== SIPp/sipp/regress/github-#0458/uac.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">
<scenario>
  <send retrans="500" start_txn="invite">
    <![CDATA[

      INVITE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: "Tom Jones" <sip:tom.jones@wales.uk>;tag=[pid]SIPpTag00[call_number]
      To: "Fromage" <sip:cheese@paris.fr>
      Call-ID: [call_id]
      CSeq: 1 INVITE
      Contact: sip:sipp@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <recv response="404" response_txn="invite">
    <action>
      <ereg regexp="(&quot;[^&quot;]*&quot; &lt;[^&gt;]*&gt;)" search_in="hdr" header="To:" assign_to="var"/>
    </action>
  </recv>
  <Reference variables="var"/>

  <send ack_txn="invite">
    <![CDATA[

      ACK [next_url] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      [routes]
      From: sip:[service]@[local_ip]:[local_port];tag=[pid]SIPpTag00[call_number]
      To: sip:[service]@[remote_ip]:[remote_port][peer_tag_param]
      Call-ID: [call_id]
      CSeq: [cseq] ACK
      Contact: sip:[service]@[local_ip]:[local_port]
      Content-Length: 0

    ]]>
  </send>

  <!--
    If attribute escaping handling is correct in the scenario loading, then the
    test below will work. If it doesn't, then it will fail because of the XML
    entities.
  -->
  <nop>
    <action>
      <strcmp assign_to="1" variable="var" value="&quot;Fromage&quot; &lt;sip:cheese@paris.fr&gt;"/>
      <test assign_to="result" variable="1" compare="equal" value="0" /> <!-- If strcmp is successful, it returns 0 -->
    </action>
  </nop>

  <nop condexec="result" condexec_inverse="true">
    <action>
      <warning message="Matching Error: '[$var]' != '&quot;Fromage&quot; &lt;sip:cheese@paris.fr&gt;'"/>
      <exec int_cmd="stop_now" />
    </action>
  </nop>

  <timewait milliseconds="500"/>
</scenario>

=== SIPp/sipp/sipp_scenarios/pfca_uac_apattern_g711a.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<!-- UC360 INVITE/200/ACK/BYE/200 sample UAC scenario -->

<scenario name="Basic UC360 UAC">

  <send retrans="500">
    <![CDATA[

      INVITE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: 16001 <sip:16001@[remote_ip]:[remote_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>
      Call-ID: [call_id]
      CSeq: 10 INVITE
      Contact: <sip:16001@[local_ip]:[local_port]>
      Content-Type: application/sdp
      Max-Forwards: 70
      User-Agent: VIRTUAL Mitel-UC-Endpoint (Mitel UC360 Collaboration Point/2.1.0.99;  08:00:0F:74:80:E1)
      Subject: Conference
      Session-Expires: 3600;refresher=uas
      Min-SE: 90
      Supported: 100rel
      Require: 100rel
      Content-Length: [len]

      v=0
      o=16001 0 0 IN IP[local_ip_type] [local_ip]
      s=-
      c=IN IP[media_ip_type] [media_ip]
      t=0 0
      m=audio [media_port] RTP/AVP 8 0 18 9 103 101
      a=rtcp:[media_port+1]
      a=sendrecv
      a=rtpmap:8 PCMA/8000
      a=rtpmap:0 PCMU/8000
      a=rtpmap:18 G729/8000
      a=rtpmap:9 G722/16000
      a=fmtp:9 bitrate=64000
      a=rtpmap:103 G7221/16000
      a=fmtp:103 bitrate=32000
      a=rtpmap:101 telephone-event/8000
      a=fmtp:101 0-11,16

    ]]>
  </send>

  <recv response="100"
        optional="true">
  </recv>

  <recv response="180">
    <action>
      <!-- NOTE:  Save the 180 Ringing's CSeq header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="CSeq:" check_it="true" assign_to="1" />
      <!-- NOTE:  Save the 180 Ringing's RSeq header for later reuse -->
      <ereg regexp=".*" search_in="hdr" header="RSeq:" check_it="true" assign_to="2" />
    </action>
  </recv>

  <!-- Send PRACK for 180 Ringing -->
  <send retrans="500">
    <![CDATA[

      PRACK sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch]
      From: 16001 <sip:16001@[local_ip]:[local_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 11 PRACK
      RAck: [$2][$1]
      Contact: <sip:16001@[local_ip]:[local_port]>
      Max-Forwards: 70
      Subject: Conference
      Content-Length: 0

    ]]>
  </send>

  <!-- receive 200 OK / PRACK (180 Ringing) -->
  <recv response="200">
  </recv>

  <!-- receive 200 OK / INVITE -->
  <recv response="200">
  </recv>

  <!-- NOTE:  [branch-5] is used to specify reuse of same [branch] value that was used five messages earlier (e.g. INVITE) -->
  <send>
    <![CDATA[

      ACK sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch-5]
      From: "16001" <sip:16001@[remote_ip]:[remote_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]:[remote_port]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 10 ACK
      Content-Length: 0

    ]]>
  </send>

  <nop>
      <action>
          <exec rtp_stream="apattern,1,8,PCMA/8000" />
      </action>
  </nop>

  <pause milliseconds="2000" />

  <nop>
      <action>
          <exec rtp_stream="pauseapattern"/>
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="resumeapattern"/>
      </action>
  </nop>

  <nop>
      <action>
          <exec rtp_stream="apattern,2,8,PCMA/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="apattern,3,8,PCMA/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="apattern,4,8,PCMA/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="apattern,5,8,PCMA/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <nop>
      <action>
          <exec rtp_stream="apattern,6,8,PCMA/8000" />
      </action>
  </nop>

  <pause milliseconds="2000"/>

  <send retrans="500">
    <![CDATA[

      BYE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
      Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch-1]
      From: "16001" <sip:16001@[remote_ip]:[remote_port]>;tag=[call_number]
      To: <sip:[service]@[remote_ip]>[peer_tag_param]
      Call-ID: [call_id]
      CSeq: 12 BYE
      Contact: <sip:16001@[local_ip]:[local_port]>
      Max-Forwards: 70
      Subject: Conference
      User-Agent: VIRTUAL Mitel-UC-Endpoint (Mitel UC360 Collaboration Point/2.1.0.99;  08:00:0F:74:80:E1)
      Content-Length: 0

    ]]>
  </send>

  <recv response="200">
  </recv>

  <!-- definition of the response time repartition table (unit is ms)   -->
  <ResponseTimeRepartition value="10, 20, 30, 40, 50, 100, 150, 200"/>

  <!-- definition of the call length repartition table (unit is ms)     -->
  <CallLengthRepartition value="10, 50, 100, 500, 1000, 5000, 10000"/>

</scenario>
